In [1]:
import sqlite3
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

In [2]:
conn=sqlite3.connect('hims.db')

In [3]:
df=pd.read_sql_query('select* from patients ;',conn)

In [4]:
df

,patient_id,fullname,dob,age,gender,marital_status,mobile,email,aadhaar,address,...,family_history,has_insurance,insurance_provider,policy_number,insurance_validity,department,preferred_doctor,appointment_date,appointment_time,created_at
0,PAT20260608084220,kunal,30121995,30,male,single,8860065479,kunal.rwd@gmail.com,123456789101,267,...,no,no,,,,cardiology,rakesh,08-06-2026,02:00,2026-06-08 08:42:20
1,PAT20260812134601,raam,1995-12-1,31,male,married,8860065479,kunal.rwd@gmail.com,999999999999,267,...,sigar and bp,yes,aditya birla,9999999999,2026-12-08,physiology,madan,no,no,2026-08-12 13:46:01
2,PAT20260824135034,Hari Prasad,1995-12-30,30,male,single,9999999999,k@gmail.com,123456789101,121,...,no,no,,,,physician,madan,2026-08-10,12:00,2026-08-24 13:50:34

In [8]:
cur=conn.cursor()
cur.execute("""
UPDATE patients
SET fullname = ?,
    age = ?,
    gender = ?,
    email = ?
WHERE rowid = (SELECT rowid FROM patients ORDER BY rowid LIMIT 1)
""", ('Sana Bhatia', 31, 'Male', 'sana@gmail.com'))
conn.commit()

In [6]:
df

,patient_id,fullname,dob,age,gender,marital_status,mobile,email,aadhaar,address,...,family_history,has_insurance,insurance_provider,policy_number,insurance_validity,department,preferred_doctor,appointment_date,appointment_time,created_at
0,PAT20260608084220,kunal,30121995,30,male,single,8860065479,kunal.rwd@gmail.com,123456789101,267,...,no,no,,,,cardiology,rakesh,08-06-2026,02:00,2026-06-08 08:42:20
1,PAT20260812134601,raam,1995-12-1,31,male,married,8860065479,kunal.rwd@gmail.com,999999999999,267,...,sigar and bp,yes,aditya birla,9999999999,2026-12-08,physiology,madan,no,no,2026-08-12 13:46:01
2,PAT20260824135034,Hari Prasad,1995-12-30,30,male,single,9999999999,k@gmail.com,123456789101,121,...,no,no,,,,physician,madan,2026-08-10,12:00,2026-08-24 13:50:34

In [9]:
df=pd.read_sql_query('select* from patients ;',conn)
df

,patient_id,fullname,dob,age,gender,marital_status,mobile,email,aadhaar,address,...,family_history,has_insurance,insurance_provider,policy_number,insurance_validity,department,preferred_doctor,appointment_date,appointment_time,created_at
0,PAT20260608084220,Sana Bhatia,30121995,31,Male,single,8860065479,sana@gmail.com,123456789101,267,...,no,no,,,,cardiology,rakesh,08-06-2026,02:00,2026-06-08 08:42:20
1,PAT20260812134601,raam,1995-12-1,31,male,married,8860065479,kunal.rwd@gmail.com,999999999999,267,...,sigar and bp,yes,aditya birla,9999999999,2026-12-08,physiology,madan,no,no,2026-08-12 13:46:01
2,PAT20260824135034,Hari Prasad,1995-12-30,30,male,single,9999999999,k@gmail.com,123456789101,121,...,no,no,,,,physician,madan,2026-08-10,12:00,2026-08-24 13:50:34